# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json if exists
COPY package.json ./

# Install dependencies
RUN npm install --production

# Copy all source files
COPY . .

# Ensure CLI scripts are executable
RUN chmod +x bin/task-manager bin/task-manager-mcp bin/agentic-control-framework-mcp

# Default command (can be overridden by MCP runner)
CMD ["node", "bin/agentic-control-framework-mcp"]
