name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_heavy:
        description: 'Run heavy macOS tests (Playwright + AppleScript)'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-linux:
    name: Linux • Node 20 • CLI+MCP
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      # Keep CI lean: skip heavy browser downloads
      ACF_SKIP_POSTINSTALL: '0'
      ACF_SKIP_PLAYWRIGHT: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install
        run: cd agentic-control-framework && npm install --no-audit --no-fund

      - name: Make executables runnable
        run: cd agentic-control-framework && chmod +x bin/* || true

      - name: CLI tests
        run: cd agentic-control-framework && npm run -s test:cli

      - name: MCP tests (core)
        run: cd agentic-control-framework && npm test

      - name: Priority tests
        run: cd agentic-control-framework && npm run -s test:priority

      - name: Validate docs commands
        run: cd agentic-control-framework && scripts/testing/validate-doc-commands.sh

  heavy-macos:
    name: macOS • Heavy (Playwright+AppleScript)
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_heavy == true }}
    runs-on: macos-latest
    env:
      NODE_ENV: test
      # Allow Playwright setup for browser tools
      ACF_SKIP_POSTINSTALL: '0'
      ACF_SKIP_PLAYWRIGHT: '0'
      # Enable gated test suites
      ACF_ENABLE_BROWSER_TOOLS: '1'
      ACF_ENABLE_APPLESCRIPT: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install
        run: cd agentic-control-framework && npm install --no-audit --no-fund

      - name: Install Playwright browsers
        run: |
          cd agentic-control-framework
          npx playwright install || true

      - name: Make executables runnable
        run: cd agentic-control-framework && chmod +x bin/* || true

      - name: MCP tests (heavy)
        run: cd agentic-control-framework && npm test
