name: ACF CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '18.x', '20.x' ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Make test scripts executable
        run: chmod +x test/cli/test-commands.sh

      - name: Run CLI Tests
        run: bash test/cli/test-commands.sh

      - name: Run MCP Tests
        run: node test/mcp/test-tools.js 